MvcStok/Controllers/MusterıController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.Entity;
namespace MvcStok.Controllers
{
    public class MusterıController : Controller
    {
        MvcDbStokEntities db = new MvcDbStokEntities();
        public ActionResult Index(string p)
        {
            var degerler = from d in db.TBLMUSTERILER select d;
            if (!string.IsNullOrEmpty(p)) 
            {
                degerler = degerler.Where(m => m.MUSTERIAD.Contains(p));
            }
            return View(degerler.ToList());
            //var degerler = db.TBLMUSTERILER.ToList();

        }
        [HttpGet] 
        public ActionResult YeniMusteri()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniMusteri(TBLMUSTERILER p)
        {      
            if(!ModelState.IsValid)
            {
                return View("YeniMusteri");
            }
            db.TBLMUSTERILER.Add(p);
            db.SaveChanges(); 
            return View();
        } 
        public ActionResult Sil(int id)
        {
            var mstr = db.TBLMUSTERILER.Find(id);
            db.TBLMUSTERILER.Remove(mstr);
            db.SaveChanges();
            return RedirectToAction("Index"); 
        }  
        public ActionResult MusteriGetir(int id)
        {
            var mus = db.TBLMUSTERILER.Find(id);
            return View("MusteriGetir",mus);
        } 
        public ActionResult Güncelle(TBLMUSTERILER p)
        {
            var musteri = db.TBLMUSTERILER.Find(p.MUSTERIID);
            musteri.MUSTERIAD = p.MUSTERIAD;
            musteri.MUSTERISOYAD = p.MUSTERISOYAD;
            db.SaveChanges();
            return RedirectToAction("Index"); 
        }
    }
}

MvcStok/Views/Musterı/Index.cshtml
@using MvcStok.Models.Entity
@model List<TBLMUSTERILER>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@using (Html.BeginForm("Index","Musterı",FormMethod.Get))
            {
                <p>
                    Aranacak Müşteri Adı: @Html.TextBox("p") 
                    <input type="submit" value="Ara" />
                </p>
            }
<table class="table table-bordered">
    <tr>
        <th>Müşteri ID</th>
        <th>Müşteri Ad</th>
        <th>Müşteri Soyad</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Alert</th>
    </tr>
    <tbody>
        @foreach (var mstr in Model)
        {
            <tr>
                <th>@mstr.MUSTERIID</th>
                <td>@mstr.MUSTERIAD</td>
                <td>@mstr.MUSTERISOYAD</td>
                <td><a href="/Musterı/Sil/@mstr.MUSTERIID" class="btn btn-danger">Sil</a></td>
                <td><a href="/Musterı/MusteriGetir/@mstr.MUSTERIID" class="btn btn-success">Güncelle</a></td>
                <td>@Html.ActionLink("SİL", "Sil", new { id = mstr.MUSTERIID }, new { @class = "btn btn-warning", onclick = "return confirm('Gerçekten Silmek İstiyor musunuz? ')" })</td>
            </tr>
        }
    </tbody>
</table>
<a href="/Musterı/YeniMusteri/" class="btn btn-primary">YENİ MÜŞTERİ EKLE</a>

MvcStok/Views/Musterı/MusteriGetir.cshtml
@model MvcStok.Models.Entity.TBLMUSTERILER
@{
    ViewBag.Title = "MusteriGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Güncelle", "Musterı", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.MUSTERIID)
        @Html.TextBoxFor(m => m.MUSTERIID, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.MUSTERIAD)
        @Html.TextBoxFor(m => m.MUSTERIAD, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.MUSTERISOYAD)
        @Html.TextBoxFor(m => m.MUSTERISOYAD, new { @class = "form-control" })
    </div> 
    <button class="btn btn-warning">Müşteri Güncelle</button>
}

MvcStok/Views/Musterı/YeniMusteri.cshtml
@model MvcStok.Models.Entity.TBLMUSTERILER
@{
    ViewBag.Title = "YeniMusteri";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form method="post" class="form-group">
   <div>
    <label>Müşteri Adı</label>
    @Html.TextBoxFor(m => m.MUSTERIAD, new { @class = "form-control" })
    @Html.ValidationMessageFor(m => m.MUSTERIAD, "", new { @style = "Color:green" })
    </div>
    <div style="margin-top:15px">
        <label>Müşteri SOYADI</label>
        <input type="text" class="form-control" name="MUSTERISOYAD" />
    </div> 
    <div style="margin-top:15px">
        <button class="btn btn-info" id="btn1">Müşteri Ekle</button> 
    </div> 
    <script>
        $('#btn1').click(function () {
            alert('Müşteri Ekleme İşlemi Yapıldı...');
        });
    </script>
</form>